In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [2]:
# put this at the top of every notebook
import plotly.io as pio
pio.renderers.default = "notebook_connected"
#pio.renderers.default = "browser"   # always opens in browser, no nbformat needed

In [3]:
from yfinance_api3.classes.stock_client import StockClient
from yfinance_api3.classes.quant_analytics import QuantAnalytics as qa
client = StockClient(ttl_price=60, ttl_info=900)
quant = qa(client)

In [4]:
symbols = ["AAPL", "MSFT", "GOOGL", "NVDA"]

In [5]:
quant.volatility_bulk (symbols=symbols, period = '1y', interval = '1d')

{'AAPL': 0.23266458580848098,
 'MSFT': 0.238577553510989,
 'GOOGL': 0.2965212448983594,
 'NVDA': 0.33771536888200615}

In [6]:
quant.var (symbol='AAPL', period = '20y', confidence = 0.95, method = 'historical', horizon = 1)

np.float64(0.029406635683260938)

In [7]:
quant.stock_report (symbol='AAPL', benchmark = 'SPY', period= '20y', risk_free_rate= 0.01)

{'symbol': 'AAPL',
 'period': '20y',
 'annualised_volatility': 0.314338116168548,
 'max_drawdown': -0.6086674427720501,
 'sharpe_ratio': 0.9067771245451193,
 'sortino_ratio': 1.2551075345360234,
 'beta': 1.0648567818558554,
 'calmar_ratio': 0.4568620117603493,
 'var_95_1d': np.float64(0.029406635683260938),
 'cvar_95_1d': 0.044937407464620646}

In [8]:
quant.sortino_ratio (symbol='AAPL', period = '20y', risk_free_rate = 0.01, interval = '1d')

1.2551075345360234

In [9]:
quant.sharpe_ratio (symbol='AAPL', period = '20y', risk_free_rate = 0.01, interval = '1d')

0.9067771245451193

In [11]:
quant.rolling_volatility_df (symbols=symbols, period = '1y', window = 21, interval= '1d', annualise= True)

                AAPL      MSFT     GOOGL      NVDA
date
2025-06-03  0.308466  0.143558  0.384483  0.372953
2025-06-04  0.286575  0.143567  0.386227  0.368971
2025-06-05  0.289379  0.140198  0.385370  0.375930
2025-06-06  0.290799  0.139723  0.281166  0.368598
2025-06-09  0.294296  0.137420  0.279278  0.367998
...              ...       ...       ...       ...
2026-04-27  0.261721  0.316248  0.300807  0.318517
2026-04-28  0.253902  0.293289  0.278008  0.311292
2026-04-29  0.250673  0.301333  0.275931  0.316226
2026-04-30  0.234644  0.332227  0.378989  0.337165
2026-05-01  0.254680  0.333598  0.373923  0.339678

[230 rows x 4 columns]

In [12]:
quant.rolling_volatility (symbol='AAPL', period = '1y', window = 21, interval = '1d', annualise = True)

date
2025-06-02    0.333038
2025-06-03    0.308466
2025-06-04    0.286575
2025-06-05    0.289379
2025-06-06    0.290799
                ...
2026-04-27    0.261721
2026-04-28    0.253902
2026-04-29    0.250673
2026-04-30    0.234644
2026-05-01    0.254680
Name: AAPL_vol_21d, Length: 231, dtype: float64

In [13]:
quant.rolling_sharpe_df (symbols=symbols, period= '1y', window = 63, risk_free_rate = 0.01, interval= '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-08-04 -0.083952  5.573188  2.510062  6.030698
2025-08-05  0.453439  4.986343  2.467730  5.967629
2025-08-06  1.294327  5.027676  2.653866  6.096758
2025-08-07  1.965128  4.779050  4.339551  5.862508
2025-08-08  2.425430  4.578601  4.403226  5.969380
...              ...       ...       ...       ...
2026-04-27  0.825792 -0.978869  0.816220  1.750230
2026-04-28  0.831571 -1.116578  0.739463  1.459573
2026-04-29  0.911923 -1.267518  0.684810  1.093532
2026-04-30  0.869108 -0.675354  1.635782  0.534832
2026-05-01  1.263010 -0.355206  1.671278  0.550903

[188 rows x 4 columns]

In [14]:
quant.rolling_returns_stats (symbol='AAPL', hold_years = 5.0, period = '20y')

{'symbol': 'AAPL',
 'hold_years': 5.0,
 'n_entries': 3773,
 'mean_return': 2.6827584799301976,
 'median_return': 2.531785691450968,
 'std_return': 1.2922197508876927,
 'min_return': 0.6693649215734052,
 'max_return': 6.293928936795194,
 'win_rate': 1.0,
 'pct_10': 1.1379790975843707,
 'pct_25': 1.4849253574246937,
 'pct_75': 3.5897318054067147,
 'pct_90': 4.608751558204148,
 'best_entry': datetime.date(2009, 1, 20),
 'worst_entry': datetime.date(2012, 9, 20),
 'cagr_mean': 0.2978803213272252,
 'prob_double': 0.954943016167506,
 'prob_halve': 0.0}

In [15]:
quant.rolling_returns_bulk (symbols=symbols, hold_years = 5.0, period = '20y')

,symbol,hold_years,n_entries,mean_return,median_return,std_return,min_return,max_return,win_rate,pct_10,pct_25,pct_75,pct_90,best_entry,worst_entry,cagr_mean,prob_double,prob_halve
symbol,,,,,,,,,,,,,,,,,,
NVDA,NVDA,5.0,3773,8.340069,7.11062,7.929114,-0.695807,36.609504,0.869335,-0.299889,0.845375,14.255022,18.736327,2019-06-17,2007-10-23,0.5634,0.726743,0.041876
AAPL,AAPL,5.0,3773,2.682758,2.531786,1.29222,0.669365,6.293929,1.0,1.137979,1.484925,3.589732,4.608752,2009-01-20,2012-09-20,0.29788,0.954943,0.0
MSFT,MSFT,5.0,3773,1.902672,1.778115,1.241595,-0.17525,5.313613,0.971906,0.186201,1.063109,2.623119,3.806743,2016-11-14,2007-12-24,0.237541,0.768884,0.0
GOOGL,GOOGL,5.0,3773,1.429056,1.50729,0.654259,-0.110036,3.125235,0.994964,0.384734,1.004056,1.825759,2.316229,2009-03-09,2007-11-07,0.194229,0.753777,0.0

In [16]:
quant.rolling_returns (symbol='AAPL', hold_years = 5.0, period = '20y')

date
2006-05-01    3.975290
2006-05-02    3.861772
2006-05-03    3.913831
2006-05-04    3.874876
2006-05-05    3.822090
                ...
2021-04-20    1.064118
2021-04-21    1.081929
2021-04-22    1.102344
2021-04-23    1.074112
2021-04-26    1.134942
Name: AAPL_5.0y_return, Length: 3773, dtype: float64

In [17]:
quant.rolling_beta_df (symbols=symbols, benchmark = 'SPY', period = '1y', window = 63, interval = '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-08-01  1.187034  0.749116  0.750549  1.512789
2025-08-04  1.334308  0.744807  0.800198  1.546466
2025-08-05  1.276875  0.777696  0.807503  1.555041
2025-08-06  1.372172  0.752733  0.805773  1.557786
2025-08-07  1.355822  0.762294  0.854238  1.541877
...              ...       ...       ...       ...
2026-04-27  0.971680  1.194978  1.284481  1.825553
2026-04-28  0.951835  1.165048  1.280987  1.832167
2026-04-29  0.951382  1.166359  1.281334  1.835501
2026-04-30  0.946197  1.038746  1.421456  1.729680
2026-05-01  0.961675  1.042437  1.421913  1.724970

[189 rows x 4 columns]

In [18]:
quant.returns_df (symbols=symbols, period = '1y', method = 'log', interval = '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-05-02 -0.038078  0.022960  0.016783  0.025564
2025-05-05 -0.031964  0.002043  0.001097 -0.005957
2025-05-06 -0.001912 -0.006579 -0.005986 -0.002463
2025-05-07 -0.011450  0.000092 -0.075367  0.030531
2025-05-08  0.006299  0.011061  0.018976  0.002645
...              ...       ...       ...       ...
2026-04-27 -0.012810  0.000471  0.017100  0.039263
2026-04-28  0.011517  0.010374 -0.001600 -0.016009
2026-04-29 -0.001997 -0.011222  0.000457 -0.018560
2026-04-30  0.004358 -0.040090  0.094962 -0.047365
2026-05-01  0.031880  0.016200  0.002310 -0.005628

[251 rows x 4 columns]

In [21]:
quant.returns_bulk (symbols=symbols, period = '1y', method = 'log', interval = '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-25  0.004358  0.011680  0.016686  0.042133
2025-04-28  0.004101 -0.001762 -0.008370 -0.020753
2025-04-29  0.005079  0.007336 -0.002806  0.002664
2025-04-30  0.006089  0.003091 -0.008528 -0.000918
2025-05-01  0.003852  0.073486  0.015620  0.024397
...              ...       ...       ...       ...
2026-04-20  0.010381 -0.011227 -0.012546  0.001882
2026-04-21 -0.025520  0.014462 -0.015320 -0.010847
2026-04-22  0.025959  0.020442  0.020936  0.013023
2026-04-23  0.000951 -0.040469 -0.001268 -0.014224
2026-04-24 -0.008705  0.021111  0.016128  0.042320

[251 rows x 4 columns]

In [22]:
quant.returns (symbol='AAPL', period = '1y', method = 'log', interval = '1d')

date
2025-04-25    0.004358
2025-04-28    0.004101
2025-04-29    0.005079
2025-04-30    0.006089
2025-05-01    0.003852
                ...
2026-04-20    0.010381
2026-04-21   -0.025520
2026-04-22    0.025959
2026-04-23    0.000951
2026-04-24   -0.008705
Name: AAPL, Length: 251, dtype: float64

In [23]:
quant.prices_df (symbols=symbols, period = '1y', interval = '1d')

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  207.465759  384.357483  158.729614  106.404915
2025-04-25  208.371826  388.872955  161.400360  110.983856
2025-04-28  209.228104  388.188202  160.055023  108.704391
2025-04-29  210.293472  391.046295  159.606583  108.994316
2025-04-30  211.577850  392.257050  158.251266  108.894333
...                ...         ...         ...         ...
2026-04-20  273.049988  418.070007  337.420013  202.059998
2026-04-21  266.170013  424.160004  332.290009  199.880005
2026-04-22  273.170013  432.920013  339.320007  202.500000
2026-04-23  273.429993  415.750000  338.890015  199.639999
2026-04-24  271.059998  424.619995  344.399994  208.270004

[252 rows x 4 columns]

In [24]:
quant.portfolio_volatility (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y')

0.18656243118824317

In [25]:
quant.portfolio_summary (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y', risk_free_rate = 0.01)

{'symbols': ['AAPL', 'MSFT', 'GOOGL', 'NVDA'],
 'weights': [0.25, 0.25, 0.25, 0.25],
 'period': '1y',
 'annualised_return': 0.4551010969755221,
 'annualised_volatility': 0.18656243118824317,
 'sharpe_ratio': 2.385802404806845,
 'correlation_matrix': {'AAPL': {'AAPL': 1.0,
   'MSFT': 0.12919255918435732,
   'GOOGL': 0.3240502533151455,
   'NVDA': 0.2668879195499929},
  'MSFT': {'AAPL': 0.12919255918435732,
   'MSFT': 1.0,
   'GOOGL': 0.18402055167270742,
   'NVDA': 0.3983524971834822},
  'GOOGL': {'AAPL': 0.3240502533151455,
   'MSFT': 0.18402055167270742,
   'GOOGL': 1.0,
   'NVDA': 0.31630560520087064},
  'NVDA': {'AAPL': 0.2668879195499929,
   'MSFT': 0.3983524971834822,
   'GOOGL': 0.31630560520087064,
   'NVDA': 1.0}}}

In [26]:
quant.portfolio_sharpe (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y', risk_free_rate = 0.01)

2.385802404806845

In [27]:
quant.portfolio_return (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y')

0.4551010969755221

year,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
month,,,,,,,,,,
Jan,0.047747,-0.010637,0.055154,0.054010,-0.005502,-0.015712,0.110521,-0.042227,-0.057583,-0.045538
Feb,0.133778,0.068185,0.044777,-0.114701,-0.079712,-0.054066,0.023183,-0.018543,0.025873,0.019066
Mar,0.048690,-0.058050,0.097026,-0.069761,0.007339,0.057473,0.118649,-0.051286,-0.081500,-0.039329
Apr,-0.000070,-0.015020,0.056436,0.155374,0.076218,-0.097131,0.028987,-0.006706,-0.043353,0.068048
May,0.067808,0.135124,-0.124213,0.085094,-0.050497,-0.054496,0.046059,0.130222,-0.053584,NaN
Jun,-0.057214,-0.009418,0.130519,0.147386,0.099109,-0.081430,0.094330,0.095553,0.021508,NaN
Jul,0.032704,0.027984,0.076394,0.165132,0.064982,0.188634,0.012785,0.054411,0.011698,NaN
Aug,0.106999,0.200422,-0.016461,0.216569,0.042489,-0.031208,-0.042384,0.032353,0.119639,NaN
Sep,-0.060243,-0.008303,0.072961,-0.102526,-0.068037,-0.120977,-0.088678,0.017467,0.096881,NaN
Oct,0.096807,-0.030478,0.110684,-0.060012,0.058657,0.109551,-0.002570,-0.030429,0.061815,NaN
Nov,0.020278,-0.181198,0.077554,0.095493,0.105082,-0.033027,0.113780,0.051707,0.032364,NaN
Dec,-0.015246,-0.116698,0.098783,0.114574,0.074228,-0.122273,0.013583,0.055155,-0.025067,NaN

In [30]:
quant.monte_carlo_bulk (symbols=symbols, horizon_years = 2.0, n_sims= 10000, target_gain = 0.3, max_drawdown_limit = 0.25, history_period = '2y', seed = None)

                            AAPL          MSFT         GOOGL          NVDA
entry_price           271.059998    424.619995    344.399994    208.270004
horizon_years           2.000000      2.000000      2.000000      2.000000
n_sims              10000.000000  10000.000000  10000.000000  10000.000000
mu_annual               0.242133      0.026440      0.392493      0.483588
sigma_annual            0.282243      0.247656      0.301084      0.486193
target_gain             0.300000      0.300000      0.300000      0.300000
max_drawdown_limit      0.250000      0.250000      0.250000      0.250000
prob_gain               0.638100      0.224500      0.841900      0.750200
prob_drawdown_ok        0.390400      0.245900      0.490600      0.030500
prob_both               0.358800      0.147700      0.480000      0.030500
prob_loss               0.150600      0.508200      0.050300      0.144100
median_return           0.502416     -0.007473      0.992898      1.069421
percentile_10          -0.097503     -0.364771      0.160026     -0.141226
percentile_90           1.469277      0.569717      2.477414      3.976876
expected_return         0.616569      0.054884      1.186034      1.639308

In [31]:
quant.monte_carlo ('AAPL', horizon_years = 2.0, n_sims = 10000, target_gain = 0.3, max_drawdown_limit = 0.25, history_period= '2y', drift_override = None, volatility_override = None, seed = None, return_paths = False, n_sample_paths = 200)

{'symbol': 'AAPL',
 'entry_price': 271.05999755859375,
 'horizon_years': 2.0,
 'n_sims': 10000,
 'mu_annual': 0.24213266655667134,
 'sigma_annual': 0.2822427147406446,
 'target_gain': 0.3,
 'max_drawdown_limit': 0.25,
 'prob_gain': 0.6273,
 'prob_drawdown_ok': 0.3962,
 'prob_both': 0.3612,
 'prob_loss': 0.1653,
 'median_return': 0.4913379161804642,
 'percentile_10': -0.10597771455551631,
 'percentile_90': 1.4814156609847107,
 'expected_return': 0.6128017519747758}

In [32]:
quant.metrics_df (symbols=symbols, benchmark = 'SPY', period = '1y', risk_free_rate = 0.01)

                           AAPL      MSFT     GOOGL      NVDA
annualised_volatility  0.232934  0.246409  0.282320  0.334727
max_drawdown          -0.137985 -0.339101 -0.203665 -0.202144
sharpe_ratio           1.221510  0.490539  2.845989  2.146843
sortino_ratio          1.923324  0.609000  4.964407  3.523169
beta                   1.005953  0.957876  1.192233  1.786144
calmar_ratio           2.221461  0.308913  5.743401  4.735906
var_95_1d              0.021379  0.023445  0.023142  0.033032
cvar_95_1d             0.030812  0.035383  0.031772  0.040536

In [33]:
quant.max_drawdown ('AAPL', period= '1y')

-0.13798524235020476

In [34]:
quant.kelly_portfolio (symbols=symbols, period = '2y', fractional = 0.5, risk_free_rate = 0.05, normalise = True)

symbol
GOOGL    0.443178
AAPL     0.300506
NVDA     0.244332
MSFT     0.011983
Name: kelly_weight, dtype: float64

In [35]:
quant.kelly_bulk (symbols=symbols, period = '2y', fractional = 0.5, risk_free_rate = 0.05)

,full_kelly,fractional_kelly,mu_annual,sigma_annual,sharpe_ratio,has_edge,suggested_max
symbol,,,,,,,
GOOGL,4.2382,2.1191,0.3882,0.3026,1.2827,True,0.25
AAPL,2.8739,1.4369,0.2322,0.2842,0.8169,True,0.25
NVDA,2.3366,1.1683,0.552,0.486,1.1357,True,0.25
MSFT,0.1146,0.0573,0.007,0.2472,0.0283,True,0.0573

In [36]:
quant.kelly ('AAPL', period = '2y', fractional = 1.0, risk_free_rate = 0.05)

{'symbol': 'AAPL',
 'period': '2y',
 'full_kelly': 2.8739,
 'fractional_kelly': 2.8739,
 'fraction_label': 'Full Kelly',
 'mu_annual': 0.2322,
 'sigma_annual': 0.2842,
 'sharpe_ratio': 0.8169,
 'edge': 0.2322,
 'has_edge': True,
 'suggested_max': 0.25}

In [37]:
quant.historical_volatility (symbol='AAPL', period= '1y', interval = '1d', annualise = True)

0.23293394612896737

In [38]:
quant.drawdown_series ('AAPL', period = '1y')

date
2025-04-24    0.000000
2025-04-25    0.000000
2025-04-28    0.000000
2025-04-29    0.000000
2025-04-30    0.000000
                ...
2026-04-20   -0.045021
2026-04-21   -0.069083
2026-04-22   -0.044601
2026-04-23   -0.043692
2026-04-24   -0.051981
Name: AAPL_drawdown, Length: 252, dtype: float64

In [39]:
quant.drawdown_df (symbols=symbols, period = '1y')

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-24  0.000000  0.000000  0.000000  0.000000
2025-04-25  0.000000  0.000000  0.000000  0.000000
2025-04-28  0.000000 -0.001761 -0.008335 -0.020539
2025-04-29  0.000000  0.000000 -0.011114 -0.017926
2025-04-30  0.000000  0.000000 -0.019511 -0.018827
...              ...       ...       ...       ...
2026-04-20 -0.045021 -0.225546 -0.017552 -0.023946
2026-04-21 -0.069083 -0.214264 -0.032489 -0.034477
2026-04-22 -0.044601 -0.198037 -0.012020 -0.021821
2026-04-23 -0.043692 -0.229843 -0.013272 -0.035636
2026-04-24 -0.051981 -0.213412  0.000000  0.000000

[252 rows x 4 columns]

In [40]:
quant.cvar ('AAPL', period = '1y', confidence = 0.95)

0.030812226574150725

In [41]:
quant.cumulative_returns_df (symbols=symbols, period = '1y', interval = '1d', base = 100.0)

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  100.000000  100.000000  100.000000  100.000000
2025-04-25  100.436731  101.174811  101.682576  104.303318
2025-04-28  100.849463  100.996655  100.835010  102.161062
2025-04-29  101.362978  101.740258  100.552492  102.433535
2025-04-30  101.982058  102.055265   99.698640  102.339571
...                ...         ...         ...         ...
2026-04-20  131.612074  108.771138  212.575338  189.897241
2026-04-21  128.295876  110.355599  209.343423  187.848470
2026-04-22  131.669927  112.634730  213.772338  190.310758
2026-04-23  131.795239  108.167531  213.501442  187.622912
2026-04-24  130.652884  110.475277  216.972740  195.733444

[252 rows x 4 columns]

In [42]:
quant.covariance_matrix(symbols=symbols, period = '1y', interval= '1d', annualise = True)

           AAPL      MSFT     GOOGL      NVDA
AAPL   0.054258  0.007415  0.021310  0.020809
MSFT   0.007415  0.060718  0.012802  0.032856
GOOGL  0.021310  0.012802  0.079704  0.029891
NVDA   0.020809  0.032856  0.029891  0.112042

In [43]:
quant.correlation_matrix (symbols=symbols, period = '1y', interval= '1d')

           AAPL      MSFT     GOOGL      NVDA
AAPL   1.000000  0.129193  0.324050  0.266888
MSFT   0.129193  1.000000  0.184021  0.398352
GOOGL  0.324050  0.184021  1.000000  0.316306
NVDA   0.266888  0.398352  0.316306  1.000000

In [44]:
quant.calmar_ratio (symbol= 'AAPL', period= '3y')

0.5677111925425095

In [45]:
quant.beta_bulk (symbols=symbols, benchmark = 'SPY',period = '1y')

{'AAPL': 1.0059528228958707,
 'MSFT': 0.9578759640510612,
 'GOOGL': 1.1922329130324365,
 'NVDA': 1.786144215804333}

In [46]:
quant.beta (symbol='GE', benchmark = 'SPY', period = '1y', interval= '1d')

1.1425452723442535

In [47]:
quant.best_worst_days_impact ('SPY', period = '20y', miss_scenarios = None, initial_value = 10000.0)

,scenario,days_missed,final_value,total_return,cagr,vs_buy_hold,type,symbol,period,n_trading_days,initial_value
0,Buy & Hold,0,7.890430e+04,6.890430,0.108987,0.000000e+00,buy_and_hold,SPY,20y,5032,10000.0
1,Miss best 5 days,5,4.715875e+04,3.715875,0.080766,-3.174556e+04,miss_best,SPY,20y,5032,10000.0
2,Miss best 10 days,10,3.423791e+04,2.423791,0.063574,-4.466639e+04,miss_best,SPY,20y,5032,10000.0
3,Miss best 20 days,20,2.059349e+04,1.059349,0.036839,-5.831081e+04,miss_best,SPY,20y,5032,10000.0
4,Miss best 30 days,30,1.367685e+04,0.367685,0.015804,-6.522745e+04,miss_best,SPY,20y,5032,10000.0
5,Miss best 40 days,40,9.526676e+03,-0.047332,-0.002425,-6.937763e+04,miss_best,SPY,20y,5032,10000.0
6,Miss best 50 days,50,6.853508e+03,-0.314649,-0.018743,-7.205079e+04,miss_best,SPY,20y,5032,10000.0
7,Miss worst 5 days,5,1.293706e+05,11.937058,0.136790,5.046628e+04,miss_worst,SPY,20y,5032,10000.0
8,Miss worst 10 days,10,1.862499e+05,17.624992,0.157726,1.073456e+05,miss_worst,SPY,20y,5032,10000.0
9,Miss worst 20 days,20,3.211911e+05,31.119114,0.189756,2.422868e+05,miss_worst,SPY,20y,5032,10000.0
10,Miss worst 30 days,30,5.132326e+05,50.323259,0.218012,4.343283e+05,miss_worst,SPY,20y,5032,10000.0
11,Miss worst 40 days,40,7.949920e+05,78.499204,0.245000,7.160877e+05,miss_worst,SPY,20y,5032,10000.0
12,Miss worst 50 days,50,1.170558e+06,116.055757,0.269358,1.091653e+06,miss_worst,SPY,20y,5032,10000.0

In [48]:
quant.best_worst_days_detail('SPY', period = '20y', n = 20)

           date    return   type
rank
1    2008-10-13  0.145198   best
2    2008-10-28  0.116855   best
3    2025-04-09  0.105019   best
4    2020-03-24  0.090603   best
5    2020-03-13  0.085487   best
6    2009-03-23  0.071829   best
7    2008-11-24  0.069291   best
8    2020-04-06  0.067166   best
9    2008-11-13  0.062340   best
10   2008-10-20  0.060079   best
11   2009-03-10  0.059610   best
12   2020-03-26  0.058390   best
13   2022-11-10  0.054954   best
14   2020-03-17  0.053992   best
15   2008-11-21  0.053944   best
16   2020-03-10  0.051745   best
17   2018-12-26  0.050525   best
18   2008-12-16  0.047065   best
19   2011-08-09  0.046499   best
20   2011-08-11  0.044884   best
21   2025-04-03 -0.049281  worst
22   2008-11-14 -0.049907  worst
23   2020-03-18 -0.050633  worst
24   2008-10-24 -0.050714  worst
25   2008-10-06 -0.050934  worst
26   2009-01-20 -0.052786  worst
27   2008-10-22 -0.054455  worst
28   2008-11-06 -0.055411  worst
29   2020-06-11 -0.057649  worst
30   2025-04-04 -0.058543  worst
31   2008-11-19 -0.064079  worst
32   2011-08-08 -0.065123  worst
33   2008-10-09 -0.069839  worst
34   2008-11-20 -0.074234  worst
35   2020-03-09 -0.078095  worst
36   2008-09-29 -0.078362  worst
37   2008-12-01 -0.088578  worst
38   2020-03-12 -0.095677  worst
39   2008-10-15 -0.098448  worst
40   2020-03-16 -0.109424  worst

In [49]:
prices  = quant.prices_df(symbols, period="1y")
prices

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  207.465759  384.357483  158.729614  106.404915
2025-04-25  208.371826  388.872955  161.400360  110.983856
2025-04-28  209.228104  388.188202  160.055023  108.704391
2025-04-29  210.293472  391.046295  159.606583  108.994316
2025-04-30  211.577850  392.257050  158.251266  108.894333
...                ...         ...         ...         ...
2026-04-20  273.049988  418.070007  337.420013  202.059998
2026-04-21  266.170013  424.160004  332.290009  199.880005
2026-04-22  273.170013  432.920013  339.320007  202.500000
2026-04-23  273.429993  415.750000  338.890015  199.639999
2026-04-24  271.059998  424.619995  344.399994  208.270004

[252 rows x 4 columns]

In [50]:
returns = quant.returns_df(symbols, period="1y")
returns

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-25  0.004358  0.011680  0.016686  0.042133
2025-04-28  0.004101 -0.001762 -0.008370 -0.020753
2025-04-29  0.005079  0.007336 -0.002806  0.002664
2025-04-30  0.006089  0.003091 -0.008528 -0.000918
2025-05-01  0.003852  0.073486  0.015620  0.024397
...              ...       ...       ...       ...
2026-04-20  0.010381 -0.011227 -0.012546  0.001882
2026-04-21 -0.025520  0.014462 -0.015320 -0.010847
2026-04-22  0.025959  0.020442  0.020936  0.013023
2026-04-23  0.000951 -0.040469 -0.001268 -0.014224
2026-04-24 -0.008705  0.021111  0.016128  0.042320

[251 rows x 4 columns]

In [51]:
cum_ret = quant.cumulative_returns_df(symbols)
cum_ret

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  100.000000  100.000000  100.000000  100.000000
2025-04-25  100.436731  101.174811  101.682576  104.303318
2025-04-28  100.849463  100.996655  100.835010  102.161062
2025-04-29  101.362978  101.740258  100.552492  102.433535
2025-04-30  101.982058  102.055265   99.698640  102.339571
...                ...         ...         ...         ...
2026-04-20  131.612074  108.771138  212.575338  189.897241
2026-04-21  128.295876  110.355599  209.343423  187.848470
2026-04-22  131.669927  112.634730  213.772338  190.310758
2026-04-23  131.795239  108.167531  213.501442  187.622912
2026-04-24  130.652884  110.475277  216.972740  195.733444

[252 rows x 4 columns]

In [52]:
quant.beta('AAPL',benchmark='SPY',period='1y',interval='1d')

1.0059528228958707

In [53]:
quant.beta_bulk(symbols,benchmark='SPY',period='1y')

{'AAPL': 1.0059528228958707,
 'MSFT': 0.9578759640510612,
 'GOOGL': 1.1922329130324365,
 'NVDA': 1.786144215804333}

In [54]:
quant.returns_bulk(symbols,period='1y')

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-25  0.004358  0.011680  0.016686  0.042133
2025-04-28  0.004101 -0.001762 -0.008370 -0.020753
2025-04-29  0.005079  0.007336 -0.002806  0.002664
2025-04-30  0.006089  0.003091 -0.008528 -0.000918
2025-05-01  0.003852  0.073486  0.015620  0.024397
...              ...       ...       ...       ...
2026-04-20  0.010381 -0.011227 -0.012546  0.001882
2026-04-21 -0.025520  0.014462 -0.015320 -0.010847
2026-04-22  0.025959  0.020442  0.020936  0.013023
2026-04-23  0.000951 -0.040469 -0.001268 -0.014224
2026-04-24 -0.008705  0.021111  0.016128  0.042320

[251 rows x 4 columns]