# Quant Analytics Class

## Imports

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

In [2]:
from yfinance_api3.classes.stock_client import StockClient
from yfinance_api3.classes.quant_analytics import QuantAnalytics as qa

In [3]:
client = StockClient(ttl_price=60, ttl_info=900)

In [4]:
quant = qa(client)

## Class Methods

In [5]:
symbols = ["AAPL", "MSFT", "GOOGL", "NVDA"]

In [6]:
# all public methods (no underscore)
clase=quant
[m for m in dir(clase) if not m.startswith('_')]

# with signatures
import inspect

for name, method in inspect.getmembers(clase, predicate=inspect.ismethod):
    if not name.startswith('_'):
        print(name, inspect.signature(method))

best_worst_days_detail (symbol: 'str', period: 'str' = '20y', n: 'int' = 20) -> 'pd.DataFrame'
best_worst_days_impact (symbol: 'str', period: 'str' = '20y', miss_scenarios: 'list[int] | None' = None, initial_value: 'float' = 10000.0) -> 'pd.DataFrame'
beta (symbol: 'str', benchmark: 'str' = 'SPY', period: 'str' = '1y', interval: 'str' = '1d') -> 'float'
beta_bulk (symbols: 'list[str]', benchmark: 'str' = 'SPY', period: 'str' = '1y') -> 'dict[str, float]'
calmar_ratio (symbol: 'str', period: 'str' = '3y') -> 'float'
correlation_matrix (symbols: 'list[str]', period: 'str' = '1y', interval: 'str' = '1d') -> 'pd.DataFrame'
covariance_matrix (symbols: 'list[str]', period: 'str' = '1y', interval: 'str' = '1d', annualise: 'bool' = True) -> 'pd.DataFrame'
cumulative_returns_df (symbols: 'list[str]', period: 'str' = '1y', interval: 'str' = '1d', base: 'float' = 100.0) -> 'pd.DataFrame'
cvar (symbol: 'str', period: 'str' = '1y', confidence: 'float' = 0.95) -> 'float'
drawdown_df (symbols: 'list[str]', period: 'str' = '1y') -> 'pd.DataFrame'
drawdown_series (symbol: 'str', period: 'str' = '1y') -> 'pd.Series'
historical_volatility (symbol: 'str', period: 'str' = '1y', interval: 'str' = '1d', annualise: 'bool' = True) -> 'float'
kelly (symbol: 'str', period: 'str' = '2y', fractional: 'float' = 1.0, risk_free_rate: 'float' = 0.05) -> 'dict'
kelly_bulk (symbols: 'list[str]', period: 'str' = '2y', fractional: 'float' = 0.5, risk_free_rate: 'float' = 0.05) -> 'pd.DataFrame'
kelly_portfolio (symbols: 'list[str]', period: 'str' = '2y', fractional: 'float' = 0.5, risk_free_rate: 'float' = 0.05, normalise: 'bool' = True) -> 'pd.Series'
max_drawdown (symbol: 'str', period: 'str' = '1y') -> 'float'
metrics_df (symbols: 'list[str]', benchmark: 'str' = 'SPY', period: 'str' = '1y', risk_free_rate: 'float' = 0.05) -> 'pd.DataFrame'
monte_carlo (symbol: 'str', horizon_years: 'float' = 2.0, n_sims: 'int' = 10000, target_gain: 'float' = 0.3, max_drawdown_limit: 'float' = 0.25, history_period: 'str' = '2y', drift_override: 'float | None' = None, volatility_override: 'float | None' = None, seed: 'int | None' = None, return_paths: 'bool' = False, n_sample_paths: 'int' = 200) -> 'dict'
monte_carlo_bulk (symbols: 'list[str]', horizon_years: 'float' = 2.0, n_sims: 'int' = 10000, target_gain: 'float' = 0.3, max_drawdown_limit: 'float' = 0.25, history_period: 'str' = '2y', seed: 'int | None' = None) -> 'pd.DataFrame'
monthly_seasonality (symbol: 'str', period: 'str' = '10y') -> 'pd.DataFrame'
portfolio_return (symbols: 'list[str]', weights: 'list[float]', period: 'str' = '1y') -> 'float'
portfolio_sharpe (symbols: 'list[str]', weights: 'list[float]', period: 'str' = '1y', risk_free_rate: 'float' = 0.05) -> 'float'
portfolio_summary (symbols: 'list[str]', weights: 'list[float]', period: 'str' = '1y', risk_free_rate: 'float' = 0.05) -> 'dict'
portfolio_volatility (symbols: 'list[str]', weights: 'list[float]', period: 'str' = '1y') -> 'float'
prices_df (symbols: 'list[str]', period: 'str' = '1y', interval: 'str' = '1d') -> 'pd.DataFrame'
returns (symbol: 'str', period: 'str' = '1y', method: 'str' = 'log', interval: 'str' = '1d') -> 'pd.Series'
returns_bulk (symbols: 'list[str]', period: 'str' = '1y', method: 'str' = 'log', interval: 'str' = '1d') -> 'pd.DataFrame'
returns_df (symbols: 'list[str]', period: 'str' = '1y', method: 'str' = 'log', interval: 'str' = '1d') -> 'pd.DataFrame'
rolling_beta_df (symbols: 'list[str]', benchmark: 'str' = 'SPY', period: 'str' = '1y', window: 'int' = 63, interval: 'str' = '1d') -> 'pd.DataFrame'
rolling_returns (symbol: 'str', hold_years: 'float' = 5.0, period: 'str' = '20y') -> 'pd.Series'
rolling_returns_bulk (symbols: 'list[str]', hold_years: 'float' = 5.0, period: 'str' = '20y') -> 'pd.DataFrame'
rolling_returns_stats (symbol: 'str', hold_years: 'float' = 5.0, period: 'str' = '20y') -> 'dict'
rolling_sharpe_df (symbols: 'list[str]', period: 'str' = '1y', window: 'int' = 63, risk_free_rate: 'float' = 0.05, interval: 'str' = '1d') -> 'pd.DataFrame'
rolling_volatility (symbol: 'str', period: 'str' = '1y', window: 'int' = 21, interval: 'str' = '1d', annualise: 'bool' = True) -> 'pd.Series'
rolling_volatility_df (symbols: 'list[str]', period: 'str' = '1y', window: 'int' = 21, interval: 'str' = '1d', annualise: 'bool' = True) -> 'pd.DataFrame'
seasonality_heatmap_data (symbol: 'str', period: 'str' = '10y') -> 'pd.DataFrame'
seasonality_stats (pivot: "'pd.DataFrame'") -> 'pd.DataFrame'
sharpe_ratio (symbol: 'str', period: 'str' = '1y', risk_free_rate: 'float' = 0.05, interval: 'str' = '1d') -> 'float'
sortino_ratio (symbol: 'str', period: 'str' = '1y', risk_free_rate: 'float' = 0.05, interval: 'str' = '1d') -> 'float'
stock_report (symbol: 'str', benchmark: 'str' = 'SPY', period: 'str' = '1y', risk_free_rate: 'float' = 0.05) -> 'dict'
var (symbol: 'str', period: 'str' = '1y', confidence: 'float' = 0.95, method: 'str' = 'historical', horizon: 'int' = 1) -> 'float'
volatility_bulk (symbols: 'list[str]', period: 'str' = '1y', interval: 'str' = '1d') -> 'dict[str, float]'
weekly_seasonality (symbol: 'str', period: 'str' = '10y') -> 'pd.DataFrame'

In [7]:
quant.volatility_bulk (symbols=symbols, period = '1y', interval = '1d')

{'AAPL': 0.23337759124562588,
 'MSFT': 0.24664176952046274,
 'GOOGL': 0.28255361985340793,
 'NVDA': 0.33303185156026005}

In [8]:
quant.var (symbol='AAPL', period = '20y', confidence = 0.95, method = 'historical', horizon = 1)

np.float64(0.029406792742207016)

In [9]:
quant.stock_report (symbol='AAPL', benchmark = 'SPY', period= '20y', risk_free_rate= 0.01)

{'symbol': 'AAPL',
 'period': '20y',
 'annualised_volatility': 0.3143526308524866,
 'max_drawdown': -0.6086675535759154,
 'sharpe_ratio': 0.9105735537069739,
 'sortino_ratio': 1.2603158147862341,
 'beta': 1.0650693435349479,
 'calmar_ratio': 0.45938198654385387,
 'var_95_1d': np.float64(0.029406792742207016),
 'cvar_95_1d': 0.04493739687071536}

In [10]:
quant.sortino_ratio (symbol='AAPL', period = '20y', risk_free_rate = 0.01, interval = '1d')

1.2603158147862341

In [11]:
quant.sharpe_ratio (symbol='AAPL', period = '20y', risk_free_rate = 0.01, interval = '1d')

0.9105735537069739

In [12]:
quant.seasonality_heatmap_data (symbol='AAPL', period = '20y')

week,1,2,3,4,5,6,7,8,9,10,...,44,45,46,47,48,49,50,51,52,53
year,,,,,,,,,,,,,,,,,,,,,
2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.026365,0.061694,0.032844,0.067327,-0.003383,-0.033509,-0.006118,-0.062928,0.032117,NaN
2007,0.002475,0.112522,-0.064680,-0.035254,-0.007379,-0.017463,0.018734,0.049982,-0.041091,0.029973,...,0.017163,-0.119764,0.006168,0.030952,0.062260,0.066293,-0.020124,0.018488,0.030530,NaN
2008,-0.098984,-0.040878,-0.065609,-0.194286,0.028767,-0.061832,-0.006774,-0.041483,0.046542,-0.022157,...,0.116311,-0.086904,-0.081433,-0.084885,0.122185,0.014352,0.045426,-0.084156,-0.046556,NaN
2009,0.057569,-0.001873,-0.091080,0.073242,0.020032,0.106402,-0.005616,-0.080274,-0.020724,-0.044899,...,-0.075708,0.030982,0.052022,-0.022157,0.003351,-0.036243,0.006983,0.003904,0.069641,NaN
2010,0.005932,-0.028540,-0.039722,-0.028774,0.017703,0.025171,0.006438,0.014628,0.070032,0.034940,...,0.053657,-0.028694,-0.004221,0.026962,0.007746,0.009829,0.000156,0.009326,-0.003214,0.008085
2011,0.042039,0.036772,-0.062442,0.028710,0.030943,0.029870,-0.017626,-0.006846,0.034007,-0.022250,...,-0.011631,-0.039026,-0.025168,-0.030325,0.071870,0.010059,-0.032011,0.058553,0.004140,NaN
2012,0.042963,-0.006132,0.001167,0.064192,0.027723,0.073399,0.017632,0.040408,0.043586,-0.000018,...,-0.045034,-0.047228,-0.035426,0.083042,0.024112,-0.088897,-0.043995,0.018713,-0.018755,NaN
2013,0.034165,-0.012714,-0.039016,-0.120240,0.031236,0.053190,-0.031201,-0.020319,-0.045119,0.002904,...,-0.011275,0.006863,0.008510,-0.009886,0.069777,0.007103,-0.009981,-0.009758,0.020163,NaN
2014,-0.034119,-0.014861,0.014504,0.009988,-0.083267,0.044328,0.046779,-0.034450,0.001885,0.007981,...,0.026421,0.013729,0.047427,0.020056,0.021121,-0.033045,-0.045827,0.018683,0.019771,NaN
2015,-0.040881,0.024513,-0.053745,0.065950,0.036998,0.019114,0.068528,0.019043,-0.008031,-0.014479,...,0.003527,0.017391,-0.072030,0.061955,-0.012490,0.010356,-0.049147,-0.063174,0.018863,NaN
2016,-0.078852,0.001753,0.044168,-0.040229,-0.028866,-0.000319,0.021811,0.009059,0.062945,-0.007281,...,-0.037999,-0.003767,0.015033,0.015719,-0.016907,0.036852,0.017727,0.004743,-0.006008,-0.025641
2017,0.018045,0.009583,0.008064,0.016250,0.058466,0.027989,0.027248,0.006926,0.022830,-0.004578,...,0.057957,0.016220,-0.025877,0.028328,-0.022404,-0.009822,0.027160,0.005978,-0.033027,NaN
2018,0.034096,0.011943,0.007736,-0.038944,-0.064195,-0.021510,0.102423,0.017804,0.004046,0.021395,...,-0.040777,-0.011069,-0.053504,-0.109751,0.036508,-0.056501,-0.017865,-0.089135,0.036489,NaN
2019,-0.051014,0.027182,0.029746,0.005995,0.055527,0.027750,0.000059,0.014963,0.011563,-0.011773,...,0.037473,0.019940,0.021604,-0.014976,0.020895,0.012947,0.016402,0.015591,0.037074,NaN
2020,0.026328,0.043371,0.027068,-0.001318,-0.027646,0.036443,0.015373,-0.036621,-0.126785,0.057324,...,-0.053720,0.092180,0.004802,-0.016099,-0.006392,0.048546,0.001309,0.034719,0.041923,NaN
2021,-0.004823,-0.037183,0.093833,-0.051125,0.037923,-0.010164,-0.040629,-0.066297,0.001319,-0.003212,...,0.011354,-0.008528,0.070405,-0.023295,0.032077,0.108811,-0.046308,0.030034,0.007318,0.005456
2022,-0.030411,0.005228,-0.061593,0.048766,0.013383,-0.021753,-0.007946,-0.014644,-0.010191,-0.051725,...,-0.109994,0.081804,0.010621,-0.021019,-0.002026,-0.038225,-0.053813,-0.019701,-0.014637,NaN
2023,-0.002386,0.039654,0.023078,0.058461,0.058727,-0.021097,0.010198,-0.038283,0.029446,-0.016752,...,0.050113,0.056584,0.017650,0.001476,0.006685,0.023374,0.009504,-0.020094,-0.005527,NaN
2024,-0.058952,0.026162,0.030336,0.004489,-0.034144,0.017439,-0.034631,0.001152,-0.015670,-0.049705,...,-0.036731,0.019289,-0.008636,0.021644,0.032453,0.023217,0.021784,0.025632,0.004322,NaN
2025,-0.047850,-0.026750,-0.029006,-0.031307,0.059341,-0.035466,0.075732,0.003884,-0.015109,-0.011454,...,0.028727,-0.007027,0.015659,-0.003377,0.027110,-0.000251,-0.001793,-0.016566,-0.000987,NaN
2026,-0.008742,-0.042950,-0.014805,-0.029312,0.046122,0.071836,-0.079464,0.034405,-0.001512,-0.025437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
quant.rolling_volatility_df (symbols=symbols, period = '1y', window = 21, interval= '1d', annualise= True)

                AAPL      MSFT     GOOGL      NVDA
date
2025-05-27  0.335006  0.285180  0.383172  0.354461
2025-05-28  0.334467  0.288118  0.381619  0.341547
2025-05-29  0.333420  0.288569  0.381640  0.348380
2025-05-30  0.332944  0.288472  0.379525  0.374587
2025-06-02  0.333038  0.159209  0.382779  0.371825
...              ...       ...       ...       ...
2026-04-20  0.220104  0.304093  0.372993  0.350187
2026-04-21  0.242022  0.295406  0.369323  0.326248
2026-04-22  0.251975  0.300055  0.373520  0.325042
2026-04-23  0.251918  0.321293  0.337615  0.331723
2026-04-24  0.255709  0.323759  0.338270  0.351958

[230 rows x 4 columns]

In [14]:
quant.rolling_volatility (symbol='AAPL', period = '1y', window = 21, interval = '1d', annualise = True)

date
2025-05-23    0.321379
2025-05-27    0.335006
2025-05-28    0.334467
2025-05-29    0.333420
2025-05-30    0.332944
                ...
2026-04-20    0.220104
2026-04-21    0.242022
2026-04-22    0.251975
2026-04-23    0.251918
2026-04-24    0.255709
Name: AAPL_vol_21d, Length: 231, dtype: float64

In [15]:
quant.rolling_sharpe_df (symbols=symbols, period= '1y', window = 63, risk_free_rate = 0.01, interval= '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-07-28  0.483073  5.653172  2.585423  6.315060
2025-07-29  0.185315  5.698630  2.934239  6.580893
2025-07-30 -0.083360  5.572936  3.033479  6.809308
2025-07-31 -0.309865  5.945209  2.778264  6.690778
2025-08-01 -0.788631  5.582217  2.347765  5.959913
...              ...       ...       ...       ...
2026-04-20  1.117625 -0.918666  0.425866  1.030287
2026-04-21  1.282702 -0.617161  0.557434  1.423861
2026-04-22  1.601669 -0.118972  0.575615  1.255931
2026-04-23  1.573122 -0.739066  0.465370  1.003572
2026-04-24  1.455830 -0.877129  0.802895  1.282456

[188 rows x 4 columns]

In [16]:
quant.rolling_returns_stats (symbol='AAPL', hold_years = 5.0, period = '20y')

{'symbol': 'AAPL',
 'hold_years': 5.0,
 'n_entries': 3773,
 'mean_return': 2.686818558384275,
 'median_return': 2.5403825219880867,
 'std_return': 1.2920389354473216,
 'min_return': 0.6693658602167852,
 'max_return': 6.293933677259176,
 'win_rate': 1.0,
 'pct_10': 1.1405472771295444,
 'pct_25': 1.4889376700551424,
 'pct_75': 3.5935244547324774,
 'pct_90': 4.608749967179642,
 'best_entry': datetime.date(2009, 1, 20),
 'worst_entry': datetime.date(2012, 9, 20),
 'cagr_mean': 0.2981663663523697,
 'prob_double': 0.954943016167506,
 'prob_halve': 0.0}

In [17]:
quant.rolling_returns_bulk (symbols=symbols, hold_years = 5.0, period = '20y')

,symbol,hold_years,n_entries,mean_return,median_return,std_return,min_return,max_return,win_rate,pct_10,pct_25,pct_75,pct_90,best_entry,worst_entry,cagr_mean,prob_double,prob_halve
symbol,,,,,,,,,,,,,,,,,,
NVDA,NVDA,5.0,3773,8.323292,7.087168,7.933316,-0.695807,36.609498,0.86907,-0.299889,0.83926,14.255018,18.736321,2019-06-17,2007-10-23,0.562838,0.725417,0.041876
AAPL,AAPL,5.0,3773,2.686819,2.540383,1.292039,0.669366,6.293934,1.0,1.140547,1.488938,3.593524,4.60875,2009-01-20,2012-09-20,0.298166,0.954943,0.0
MSFT,MSFT,5.0,3773,1.901874,1.778115,1.242572,-0.17525,5.313613,0.971906,0.183945,1.063108,2.623119,3.806741,2016-11-14,2007-12-24,0.237473,0.768884,0.0
GOOGL,GOOGL,5.0,3773,1.426462,1.504267,0.655006,-0.110036,3.125236,0.994964,0.380632,1.002374,1.823489,2.314635,2009-03-09,2007-11-07,0.193974,0.752452,0.0

In [18]:
quant.rolling_returns (symbol='AAPL', hold_years = 5.0, period = '20y')

date
2006-04-24    4.368973
2006-04-25    4.295753
2006-04-26    4.137929
2006-04-27    3.999280
2006-04-28    3.974143
                ...
2021-04-13    1.085398
2021-04-14    1.069806
2021-04-15    1.085229
2021-04-16    1.092504
2021-04-19    1.063905
Name: AAPL_5.0y_return, Length: 3773, dtype: float64

In [19]:
quant.rolling_beta_df (symbols=symbols, benchmark = 'SPY', period = '1y', window = 63, interval = '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-07-25  1.144395  0.876540  0.745959  1.562632
2025-07-28  1.143826  0.875653  0.734607  1.511791
2025-07-29  1.158636  0.872846  0.703698  1.507479
2025-07-30  1.164889  0.873287  0.710939  1.501287
2025-07-31  1.169184  0.804692  0.745255  1.509971
...              ...       ...       ...       ...
2026-04-20  1.007086  1.059537  1.265215  1.817000
2026-04-21  0.974644  1.075282  1.280531  1.785690
2026-04-22  1.017048  1.161481  1.284538  1.760397
2026-04-23  1.016813  1.179994  1.281225  1.767844
2026-04-24  0.994089  1.199221  1.289159  1.804815

[189 rows x 4 columns]

In [20]:
quant.returns_df (symbols=symbols, period = '1y', method = 'log', interval = '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-25  0.004358  0.011680  0.016686  0.042133
2025-04-28  0.004101 -0.001762 -0.008370 -0.020753
2025-04-29  0.005079  0.007336 -0.002806  0.002664
2025-04-30  0.006089  0.003091 -0.008528 -0.000918
2025-05-01  0.003851  0.073486  0.015620  0.024397
...              ...       ...       ...       ...
2026-04-20  0.010381 -0.011227 -0.012546  0.001882
2026-04-21 -0.025520  0.014462 -0.015320 -0.010847
2026-04-22  0.025959  0.020442  0.020936  0.013023
2026-04-23  0.000951 -0.040469 -0.001268 -0.014224
2026-04-24 -0.008705  0.021111  0.016128  0.042320

[251 rows x 4 columns]

In [21]:
quant.returns_bulk (symbols=symbols, period = '1y', method = 'log', interval = '1d')

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-25  0.004358  0.011680  0.016686  0.042133
2025-04-28  0.004101 -0.001762 -0.008370 -0.020753
2025-04-29  0.005079  0.007336 -0.002806  0.002664
2025-04-30  0.006089  0.003091 -0.008528 -0.000918
2025-05-01  0.003851  0.073486  0.015620  0.024397
...              ...       ...       ...       ...
2026-04-20  0.010381 -0.011227 -0.012546  0.001882
2026-04-21 -0.025520  0.014462 -0.015320 -0.010847
2026-04-22  0.025959  0.020442  0.020936  0.013023
2026-04-23  0.000951 -0.040469 -0.001268 -0.014224
2026-04-24 -0.008705  0.021111  0.016128  0.042320

[251 rows x 4 columns]

In [22]:
quant.returns (symbol='AAPL', period = '1y', method = 'log', interval = '1d')

date
2025-04-25    0.004358
2025-04-28    0.004101
2025-04-29    0.005079
2025-04-30    0.006089
2025-05-01    0.003851
                ...
2026-04-20    0.010381
2026-04-21   -0.025520
2026-04-22    0.025959
2026-04-23    0.000951
2026-04-24   -0.008705
Name: AAPL, Length: 251, dtype: float64

In [23]:
quant.prices_df (symbols=symbols, period = '1y', interval = '1d')

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  207.465775  384.357483  158.729614  106.404915
2025-04-25  208.371811  388.872955  161.400360  110.983856
2025-04-28  209.228104  388.188202  160.055023  108.704384
2025-04-29  210.293457  391.046295  159.606567  108.994308
2025-04-30  211.577850  392.257050  158.251266  108.894333
...                ...         ...         ...         ...
2026-04-20  273.049988  418.070007  337.420013  202.059998
2026-04-21  266.170013  424.160004  332.290009  199.880005
2026-04-22  273.170013  432.920013  339.320007  202.500000
2026-04-23  273.429993  415.750000  338.890015  199.639999
2026-04-24  271.059998  424.619995  344.399994  208.270004

[252 rows x 4 columns]

In [24]:
quant.portfolio_volatility (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y')

0.1865624154512477

In [25]:
quant.portfolio_summary (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y', risk_free_rate = 0.01)

{'symbols': ['AAPL', 'MSFT', 'GOOGL', 'NVDA'],
 'weights': [0.25, 0.25, 0.25, 0.25],
 'period': '1y',
 'annualised_return': 0.45510107851514947,
 'annualised_volatility': 0.1865624154512477,
 'sharpe_ratio': 2.38580250710499,
 'correlation_matrix': {'AAPL': {'AAPL': 1.0,
   'MSFT': 0.12919264450403292,
   'GOOGL': 0.3240503639872449,
   'NVDA': 0.26688790452755357},
  'MSFT': {'AAPL': 0.12919264450403292,
   'MSFT': 1.0,
   'GOOGL': 0.18402080766442863,
   'NVDA': 0.39835252379883956},
  'GOOGL': {'AAPL': 0.3240503639872449,
   'MSFT': 0.18402080766442863,
   'GOOGL': 1.0,
   'NVDA': 0.3163054032221437},
  'NVDA': {'AAPL': 0.26688790452755357,
   'MSFT': 0.39835252379883956,
   'GOOGL': 0.3163054032221437,
   'NVDA': 1.0}}}

In [26]:
quant.portfolio_sharpe (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y', risk_free_rate = 0.01)

2.38580250710499

In [27]:
quant.portfolio_return (symbols=symbols, weights= [0.25,0.25,0.25,0.25], period = '1y')

0.45510107851514947

In [28]:
quant.weekly_seasonality ('AAPL', period= '10y')

year,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
week,,,,,,,,,,,
1,NaN,0.018045,0.034096,-0.051014,0.026328,-0.004823,-0.030411,-0.002386,-0.058952,-0.047850,-0.008742
2,NaN,0.009583,0.011943,0.027182,0.043371,-0.037183,0.005228,0.039654,0.026162,-0.026750,-0.042950
3,NaN,0.008064,0.007736,0.029746,0.027068,0.093833,-0.061593,0.023078,0.030336,-0.029006,-0.014805
4,NaN,0.016250,-0.038944,0.005995,-0.001318,-0.051125,0.048766,0.058461,0.004489,-0.031307,-0.029312
5,NaN,0.058466,-0.064195,0.055527,-0.027646,0.037923,0.013383,0.058727,-0.034144,0.059341,0.046122
6,NaN,0.027989,-0.021510,0.027750,0.036443,-0.010164,-0.021753,-0.021097,0.017439,-0.035466,0.071836
7,NaN,0.027248,0.102423,0.000059,0.015373,-0.040629,-0.007946,0.010198,-0.034631,0.075732,-0.079464
8,NaN,0.006926,0.017804,0.014963,-0.036621,-0.066297,-0.014644,-0.038283,0.001152,0.003884,0.034405
9,NaN,0.022830,0.004046,0.011563,-0.126785,0.001319,-0.010191,0.029446,-0.015670,-0.015109,-0.001512
10,NaN,-0.004578,0.021395,-0.011773,0.057324,-0.003212,-0.051725,-0.016752,-0.049705,-0.011454,-0.025437
11,NaN,0.006109,-0.010890,0.076398,-0.038266,-0.008593,0.059781,0.043771,0.011070,-0.106998,-0.028509
12,NaN,0.004643,-0.073475,0.026488,-0.175307,0.010168,0.065496,0.033871,-0.001970,0.022390,-0.008516
13,NaN,0.021473,0.017218,-0.005758,0.080701,0.014768,-0.002346,0.029017,-0.004644,-0.001695,0.003266
14,NaN,-0.002228,0.003577,0.037115,-0.025551,0.081301,-0.024210,-0.001455,-0.011080,-0.135475,0.028617
15,NaN,-0.015975,0.037712,0.009492,0.110103,0.008722,-0.028220,0.003340,0.041102,0.051863,0.017818
16,NaN,0.008649,-0.051565,0.025092,0.055264,0.001193,-0.021175,-0.001150,-0.065421,-0.005905,0.037431
17,NaN,0.009700,-0.020517,0.002158,0.000601,-0.021293,-0.025589,0.028239,0.026061,0.062443,0.003071
18,-0.004859,0.036965,0.132516,0.036466,0.021557,-0.007826,-0.000881,0.022926,0.083166,-0.018778,NaN
19,-0.023728,0.052257,0.029849,-0.065222,0.075758,-0.021196,-0.064661,-0.004386,-0.000446,-0.033212,NaN
20,0.051922,-0.019475,-0.012090,-0.041485,-0.007803,-0.015850,-0.064714,0.015008,0.037257,0.065517,NaN
21,0.053875,0.003593,0.012184,-0.053069,0.036333,-0.006538,0.087579,0.001542,0.000579,-0.075689,NaN
22,-0.024216,0.011979,0.008803,-0.021791,-0.002979,0.010272,-0.028468,0.031465,0.011949,0.028576,NaN
23,0.009293,-0.041621,0.007674,0.086137,0.042649,0.011597,-0.056748,0.000055,0.024135,0.015285,NaN
24,-0.035414,-0.045040,-0.014919,0.013621,0.022021,0.024421,-0.040618,0.021883,0.079232,-0.036632,NaN
25,-0.020246,0.028186,-0.020758,0.031337,0.032231,0.020313,0.076771,0.009518,-0.023531,0.023161,NaN
26,0.026660,-0.015450,0.001027,-0.004326,0.011180,0.051462,-0.019271,0.039051,0.015085,0.000398,NaN
27,0.008238,0.001111,0.015451,0.031882,0.029636,0.036796,0.058375,-0.016961,0.074637,0.062015,NaN
28,0.021721,0.033708,0.017875,-0.004554,0.053748,0.008821,0.021287,0.000052,0.018556,-0.011192,NaN
29,-0.001215,0.008253,0.000575,-0.003493,0.004248,0.014823,0.026104,0.006555,-0.027023,0.000095,NaN
30,0.056254,-0.005124,-0.002403,0.025421,-0.038541,-0.018174,0.054643,0.020267,-0.028309,0.012785,NaN
31,0.036966,0.046087,0.089067,-0.017907,0.147331,0.003421,0.018889,-0.070673,0.008717,-0.053769,NaN
32,0.006513,0.010924,0.001288,-0.011108,0.047551,0.020255,0.040823,-0.021759,-0.016465,0.133264,NaN
33,0.010908,0.000127,0.048427,0.027414,0.034155,-0.006104,-0.003370,-0.018561,0.046576,0.010913,NaN
34,-0.022129,0.014984,-0.006526,-0.018692,0.082349,0.002767,-0.046058,0.023612,0.003495,-0.016538,NaN
35,0.007388,0.026211,0.053062,0.030102,0.003518,0.038358,-0.047733,0.060747,0.009522,0.019231,NaN
36,-0.042699,-0.033039,-0.027808,0.021654,-0.030828,-0.034543,0.010012,-0.059538,-0.035721,0.032523,NaN
37,0.114321,0.007880,0.011478,0.025743,-0.074074,-0.019534,-0.042384,-0.017791,0.007608,-0.023447,NaN
38,-0.019231,-0.049975,-0.027609,-0.004663,-0.046072,0.005889,-0.001792,-0.001257,0.025618,0.048832,NaN
39,0.003016,0.014681,0.037122,0.005006,0.050917,-0.029064,-0.081300,-0.020482,-0.001797,0.040570,NaN
40,0.008934,0.007656,-0.006423,0.037428,0.006591,0.001752,0.013676,0.036680,-0.004346,0.010021,NaN
41,0.031299,0.010882,-0.009719,0.040527,0.034949,0.013576,-0.012206,0.007663,0.003307,-0.049415,NaN
42,-0.008756,-0.004714,-0.012607,0.000847,0.017526,0.026581,0.064243,-0.033380,0.032740,0.028621,NaN
43,-0.024700,0.043520,-0.013725,0.043018,-0.033440,0.007465,0.057513,-0.026955,-0.015277,0.041738,NaN
44,-0.037999,0.057957,-0.040777,0.037473,-0.053720,0.011354,-0.109994,0.050113,-0.036731,0.028727,NaN
45,-0.003767,0.016220,-0.011069,0.019940,0.092180,-0.008528,0.081804,0.056584,0.019289,-0.007027,NaN
46,0.015033,-0.025877,-0.053504,0.021604,0.004802,0.070405,0.010621,0.017650,-0.008636,0.015659,NaN
47,0.015719,0.028328,-0.109751,-0.014976,-0.016099,-0.023295,-0.021019,0.001476,0.021644,-0.003377,NaN
48,-0.016907,-0.022404,0.036508,0.020895,-0.006392,0.032077,-0.002026,0.006685,0.032453,0.027110,NaN
49,0.036852,-0.009822,-0.056501,0.012947,0.048546,0.108811,-0.038225,0.023374,0.023217,-0.000251,NaN
50,0.017727,0.027160,-0.017865,0.016402,0.001309,-0.046308,-0.053813,0.009504,0.021784,-0.001793,NaN
51,0.004743,0.005978,-0.089135,0.015591,0.034719,0.030034,-0.019701,-0.020094,0.025632,-0.016566,NaN
52,-0.006008,-0.033027,0.036489,0.037074,0.041923,0.007318,-0.014637,-0.005527,0.004322,-0.000987,NaN
53,NaN,NaN,NaN,NaN,NaN,0.005456,NaN,NaN,NaN,NaN,NaN

In [29]:
quant.monthly_seasonality ('AAPL', period= '10y')

year,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
month,,,,,,,,,,
Jan,0.047747,-0.010636,0.055154,0.054010,-0.005501,-0.015712,0.110521,-0.042227,-0.057583,-0.045538
Feb,0.133778,0.068185,0.044777,-0.114702,-0.079712,-0.054066,0.023183,-0.018543,0.025872,0.019066
Mar,0.048690,-0.058051,0.097026,-0.069761,0.007340,0.057473,0.118649,-0.051286,-0.081500,-0.039329
Apr,-0.000069,-0.015020,0.056436,0.155374,0.076217,-0.097131,0.028987,-0.006706,-0.043353,0.068048
May,0.067807,0.135124,-0.124213,0.085094,-0.050497,-0.054496,0.046058,0.130222,-0.053584,NaN
Jun,-0.057214,-0.009418,0.130519,0.147386,0.099109,-0.081430,0.094330,0.095553,0.021509,NaN
Jul,0.032704,0.027983,0.076395,0.165132,0.064983,0.188634,0.012785,0.054411,0.011698,NaN
Aug,0.106999,0.200422,-0.016461,0.216569,0.042489,-0.031208,-0.042384,0.032354,0.119639,NaN
Sep,-0.060244,-0.008303,0.072962,-0.102526,-0.068037,-0.120977,-0.088678,0.017467,0.096881,NaN
Oct,0.096807,-0.030478,0.110684,-0.060012,0.058657,0.109551,-0.002570,-0.030429,0.061815,NaN
Nov,0.020278,-0.181198,0.077554,0.095493,0.105081,-0.033027,0.113780,0.051707,0.032364,NaN
Dec,-0.015246,-0.116699,0.098784,0.114574,0.074229,-0.122273,0.013582,0.055155,-0.025067,NaN

In [30]:
quant.monte_carlo_bulk (symbols=symbols, horizon_years = 2.0, n_sims= 10000, target_gain = 0.3, max_drawdown_limit = 0.25, history_period = '2y', seed = None)

                            AAPL          MSFT         GOOGL          NVDA
entry_price           271.059998    424.619995    344.399994    208.270004
horizon_years           2.000000      2.000000      2.000000      2.000000
n_sims              10000.000000  10000.000000  10000.000000  10000.000000
mu_annual               0.242133      0.026440      0.392493      0.483588
sigma_annual            0.282243      0.247656      0.301084      0.486193
target_gain             0.300000      0.300000      0.300000      0.300000
max_drawdown_limit      0.250000      0.250000      0.250000      0.250000
prob_gain               0.634900      0.214700      0.845500      0.759000
prob_drawdown_ok        0.397500      0.240300      0.497500      0.032100
prob_both               0.364700      0.142800      0.485600      0.032100
prob_loss               0.161500      0.507800      0.052000      0.138600
median_return           0.492972     -0.007654      1.001526      1.070998
percentile_10          -0.110619     -0.373953      0.163420     -0.132964
percentile_90           1.485046      0.546139      2.459659      4.045640
expected_return         0.615152      0.049527      1.191238      1.651814

In [31]:
quant.monte_carlo ('AAPL', horizon_years = 2.0, n_sims = 10000, target_gain = 0.3, max_drawdown_limit = 0.25, history_period= '2y', drift_override = None, volatility_override = None, seed = None, return_paths = False, n_sample_paths = 200)

{'symbol': 'AAPL',
 'entry_price': 271.05999755859375,
 'horizon_years': 2.0,
 'n_sims': 10000,
 'mu_annual': 0.24213266655667068,
 'sigma_annual': 0.28224275266480964,
 'target_gain': 0.3,
 'max_drawdown_limit': 0.25,
 'prob_gain': 0.6441,
 'prob_drawdown_ok': 0.4088,
 'prob_both': 0.3737,
 'prob_loss': 0.1603,
 'median_return': 0.5017884831271565,
 'percentile_10': -0.09720143801235866,
 'percentile_90': 1.4925634646429822,
 'expected_return': 0.6208180504367996}

In [32]:
quant.metrics_df (symbols=symbols, benchmark = 'SPY', period = '1y', risk_free_rate = 0.01)

                           AAPL      MSFT     GOOGL      NVDA
annualised_volatility  0.232934  0.246409  0.282320  0.334727
max_drawdown          -0.137985 -0.339101 -0.203665 -0.202144
sharpe_ratio           1.221510  0.490539  2.845990  2.146843
sortino_ratio          1.923324  0.609000  4.964408  3.523169
beta                   1.005954  0.957876  1.192234  1.786145
calmar_ratio           2.221460  0.308913  5.743401  4.735906
var_95_1d              0.021379  0.023445  0.023142  0.033032
cvar_95_1d             0.030812  0.035383  0.031772  0.040536

In [33]:
quant.max_drawdown ('AAPL', period= '1y')

-0.13798524235020476

In [34]:
quant.kelly_portfolio (symbols=symbols, period = '2y', fractional = 0.5, risk_free_rate = 0.05, normalise = True)

symbol
GOOGL    0.443178
AAPL     0.300506
NVDA     0.244332
MSFT     0.011983
Name: kelly_weight, dtype: float64

In [35]:
quant.kelly_bulk (symbols=symbols, period = '2y', fractional = 0.5, risk_free_rate = 0.05)

,full_kelly,fractional_kelly,mu_annual,sigma_annual,sharpe_ratio,has_edge,suggested_max
symbol,,,,,,,
GOOGL,4.2382,2.1191,0.3882,0.3026,1.2827,True,0.25
AAPL,2.8739,1.4369,0.2322,0.2842,0.8169,True,0.25
NVDA,2.3366,1.1683,0.552,0.486,1.1357,True,0.25
MSFT,0.1146,0.0573,0.007,0.2472,0.0283,True,0.0573

In [36]:
quant.kelly ('AAPL', period = '2y', fractional = 1.0, risk_free_rate = 0.05)

{'symbol': 'AAPL',
 'period': '2y',
 'full_kelly': 2.8739,
 'fractional_kelly': 2.8739,
 'fraction_label': 'Full Kelly',
 'mu_annual': 0.2322,
 'sigma_annual': 0.2842,
 'sharpe_ratio': 0.8169,
 'edge': 0.2322,
 'has_edge': True,
 'suggested_max': 0.25}

In [37]:
quant.historical_volatility (symbol='AAPL', period= '1y', interval = '1d', annualise = True)

0.2329339288380674

In [38]:
quant.drawdown_series ('AAPL', period = '1y')

date
2025-04-24    0.000000
2025-04-25    0.000000
2025-04-28    0.000000
2025-04-29    0.000000
2025-04-30    0.000000
                ...
2026-04-20   -0.045021
2026-04-21   -0.069083
2026-04-22   -0.044601
2026-04-23   -0.043692
2026-04-24   -0.051981
Name: AAPL_drawdown, Length: 252, dtype: float64

In [39]:
quant.drawdown_df (symbols=symbols, period = '1y')

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-24  0.000000  0.000000  0.000000  0.000000
2025-04-25  0.000000  0.000000  0.000000  0.000000
2025-04-28  0.000000 -0.001761 -0.008335 -0.020539
2025-04-29  0.000000  0.000000 -0.011114 -0.017926
2025-04-30  0.000000  0.000000 -0.019511 -0.018827
...              ...       ...       ...       ...
2026-04-20 -0.045021 -0.225546 -0.017552 -0.023946
2026-04-21 -0.069083 -0.214264 -0.032489 -0.034477
2026-04-22 -0.044601 -0.198037 -0.012020 -0.021821
2026-04-23 -0.043692 -0.229843 -0.013272 -0.035636
2026-04-24 -0.051981 -0.213412  0.000000  0.000000

[252 rows x 4 columns]

In [40]:
quant.cvar ('AAPL', period = '1y', confidence = 0.95)

0.03081222104222158

In [41]:
quant.cumulative_returns_df (symbols=symbols, period = '1y', interval = '1d', base = 100.0)

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  100.000000  100.000000  100.000000  100.000000
2025-04-25  100.436716  101.174811  101.682576  104.303318
2025-04-28  100.849455  100.996655  100.835010  102.161055
2025-04-29  101.362963  101.740258  100.552482  102.433528
2025-04-30  101.982050  102.055265   99.698640  102.339571
...                ...         ...         ...         ...
2026-04-20  131.612064  108.771138  212.575338  189.897241
2026-04-21  128.295867  110.355599  209.343423  187.848470
2026-04-22  131.669917  112.634730  213.772338  190.310758
2026-04-23  131.795229  108.167531  213.501442  187.622912
2026-04-24  130.652874  110.475277  216.972740  195.733444

[252 rows x 4 columns]

In [42]:
quant.covariance_matrix(symbols=symbols, period = '1y', interval= '1d', annualise = True)

           AAPL      MSFT     GOOGL      NVDA
AAPL   0.054258  0.007415  0.021310  0.020809
MSFT   0.007415  0.060718  0.012802  0.032856
GOOGL  0.021310  0.012802  0.079704  0.029891
NVDA   0.020809  0.032856  0.029891  0.112042

In [43]:
quant.correlation_matrix (symbols=symbols, period = '1y', interval= '1d')

           AAPL      MSFT     GOOGL      NVDA
AAPL   1.000000  0.129193  0.324050  0.266888
MSFT   0.129193  1.000000  0.184021  0.398353
GOOGL  0.324050  0.184021  1.000000  0.316305
NVDA   0.266888  0.398353  0.316305  1.000000

In [44]:
quant.calmar_ratio (symbol= 'AAPL', period= '3y')

0.5677112260867081

In [45]:
quant.beta_bulk (symbols=symbols, benchmark = 'SPY',period = '1y')

{'AAPL': 1.0059539702958469,
 'MSFT': 0.9578764821912793,
 'GOOGL': 1.192233994233424,
 'NVDA': 1.7861453103689564}

In [46]:
quant.beta (symbol='GE', benchmark = 'SPY', period = '1y', interval= '1d')

1.1425459661861228

In [47]:
quant.best_worst_days_impact ('SPY', period = '20y', miss_scenarios = None, initial_value = 10000.0)

,scenario,days_missed,final_value,total_return,cagr,vs_buy_hold,type,symbol,period,n_trading_days,initial_value
0,Buy & Hold,0,7.890425e+04,6.890425,0.108987,0.000000e+00,buy_and_hold,SPY,20y,5032,10000.0
1,Miss best 5 days,5,4.715871e+04,3.715871,0.080766,-3.174554e+04,miss_best,SPY,20y,5032,10000.0
2,Miss best 10 days,10,3.423788e+04,2.423788,0.063574,-4.466637e+04,miss_best,SPY,20y,5032,10000.0
3,Miss best 20 days,20,2.059350e+04,1.059350,0.036839,-5.831075e+04,miss_best,SPY,20y,5032,10000.0
4,Miss best 30 days,30,1.367686e+04,0.367686,0.015805,-6.522739e+04,miss_best,SPY,20y,5032,10000.0
5,Miss best 40 days,40,9.526676e+03,-0.047332,-0.002425,-6.937757e+04,miss_best,SPY,20y,5032,10000.0
6,Miss best 50 days,50,6.853505e+03,-0.314649,-0.018743,-7.205074e+04,miss_best,SPY,20y,5032,10000.0
7,Miss worst 5 days,5,1.293703e+05,11.937033,0.136790,5.046609e+04,miss_worst,SPY,20y,5032,10000.0
8,Miss worst 10 days,10,1.862494e+05,17.624941,0.157726,1.073452e+05,miss_worst,SPY,20y,5032,10000.0
9,Miss worst 20 days,20,3.211896e+05,31.118960,0.189756,2.422854e+05,miss_worst,SPY,20y,5032,10000.0
10,Miss worst 30 days,30,5.132320e+05,50.323199,0.218012,4.343277e+05,miss_worst,SPY,20y,5032,10000.0
11,Miss worst 40 days,40,7.949912e+05,78.499118,0.245000,7.160869e+05,miss_worst,SPY,20y,5032,10000.0
12,Miss worst 50 days,50,1.170558e+06,116.055763,0.269358,1.091653e+06,miss_worst,SPY,20y,5032,10000.0

In [48]:
quant.best_worst_days_detail('SPY', period = '20y', n = 20)

           date    return   type
rank
1    2008-10-13  0.145197   best
2    2008-10-28  0.116856   best
3    2025-04-09  0.105019   best
4    2020-03-24  0.090603   best
5    2020-03-13  0.085486   best
6    2009-03-23  0.071828   best
7    2008-11-24  0.069291   best
8    2020-04-06  0.067166   best
9    2008-11-13  0.062340   best
10   2008-10-20  0.060079   best
11   2009-03-10  0.059609   best
12   2020-03-26  0.058390   best
13   2022-11-10  0.054954   best
14   2020-03-17  0.053992   best
15   2008-11-21  0.053943   best
16   2020-03-10  0.051745   best
17   2018-12-26  0.050525   best
18   2008-12-16  0.047066   best
19   2011-08-09  0.046499   best
20   2011-08-11  0.044884   best
21   2025-04-03 -0.049281  worst
22   2008-11-14 -0.049907  worst
23   2020-03-18 -0.050633  worst
24   2008-10-24 -0.050714  worst
25   2008-10-06 -0.050933  worst
26   2009-01-20 -0.052786  worst
27   2008-10-22 -0.054454  worst
28   2008-11-06 -0.055411  worst
29   2020-06-11 -0.057649  worst
30   2025-04-04 -0.058543  worst
31   2008-11-19 -0.064079  worst
32   2011-08-08 -0.065123  worst
33   2008-10-09 -0.069839  worst
34   2008-11-20 -0.074233  worst
35   2020-03-09 -0.078094  worst
36   2008-09-29 -0.078362  worst
37   2008-12-01 -0.088578  worst
38   2020-03-12 -0.095677  worst
39   2008-10-15 -0.098447  worst
40   2020-03-16 -0.109424  worst

In [49]:
prices  = quant.prices_df(symbols, period="1y")
prices

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  207.465775  384.357483  158.729614  106.404915
2025-04-25  208.371811  388.872955  161.400360  110.983856
2025-04-28  209.228104  388.188202  160.055023  108.704384
2025-04-29  210.293457  391.046295  159.606567  108.994308
2025-04-30  211.577850  392.257050  158.251266  108.894333
...                ...         ...         ...         ...
2026-04-20  273.049988  418.070007  337.420013  202.059998
2026-04-21  266.170013  424.160004  332.290009  199.880005
2026-04-22  273.170013  432.920013  339.320007  202.500000
2026-04-23  273.429993  415.750000  338.890015  199.639999
2026-04-24  271.059998  424.619995  344.399994  208.270004

[252 rows x 4 columns]

In [50]:
returns = quant.returns_df(symbols, period="1y")
returns

                AAPL      MSFT     GOOGL      NVDA
date
2025-04-25  0.004358  0.011680  0.016686  0.042133
2025-04-28  0.004101 -0.001762 -0.008370 -0.020753
2025-04-29  0.005079  0.007336 -0.002806  0.002664
2025-04-30  0.006089  0.003091 -0.008528 -0.000918
2025-05-01  0.003851  0.073486  0.015620  0.024397
...              ...       ...       ...       ...
2026-04-20  0.010381 -0.011227 -0.012546  0.001882
2026-04-21 -0.025520  0.014462 -0.015320 -0.010847
2026-04-22  0.025959  0.020442  0.020936  0.013023
2026-04-23  0.000951 -0.040469 -0.001268 -0.014224
2026-04-24 -0.008705  0.021111  0.016128  0.042320

[251 rows x 4 columns]

In [51]:
cum_ret = quant.cumulative_returns_df(symbols)
cum_ret

                  AAPL        MSFT       GOOGL        NVDA
date
2025-04-24  100.000000  100.000000  100.000000  100.000000
2025-04-25  100.436716  101.174811  101.682576  104.303318
2025-04-28  100.849455  100.996655  100.835010  102.161055
2025-04-29  101.362963  101.740258  100.552482  102.433528
2025-04-30  101.982050  102.055265   99.698640  102.339571
...                ...         ...         ...         ...
2026-04-20  131.612064  108.771138  212.575338  189.897241
2026-04-21  128.295867  110.355599  209.343423  187.848470
2026-04-22  131.669917  112.634730  213.772338  190.310758
2026-04-23  131.795229  108.167531  213.501442  187.622912
2026-04-24  130.652874  110.475277  216.972740  195.733444

[252 rows x 4 columns]

In [52]:
quant.beta('AAPL',benchmark='SPY',period='1y',interval='1d')

1.0059539702958469

In [53]:
quant.beta_bulk(symbols,benchmark='SPY',period='1y')

{'AAPL': 1.0059539702958469,
 'MSFT': 0.9578764821912793,
 'GOOGL': 1.192233994233424,
 'NVDA': 1.7861453103689564}

In [63]:
quant.returns_bulk(symbols,period='1y')

,AAPL,MSFT,NVDA,GOOGL,META,AMZN,TSLA,JPM
date,,,,,,,,
2025-04-28,0.004101,-0.001762,-0.020753,-0.008370,0.004503,-0.006849,0.003258,-0.001356
2025-04-29,0.005079,0.007336,0.002664,-0.002806,0.008513,-0.001653,0.021284,0.005740
2025-04-30,0.006089,0.003091,-0.000918,-0.008528,-0.009860,-0.015976,-0.034382,0.000000
2025-05-01,0.003851,0.073486,0.024397,0.015620,0.041408,0.030860,-0.005829,0.009237
2025-05-02,-0.038077,0.022960,0.025564,0.016783,0.042445,-0.001157,0.023569,0.022508
...,...,...,...,...,...,...,...,...
2026-04-20,0.010381,-0.011227,0.001882,-0.012546,-0.025953,-0.009141,-0.020477,0.021363
2026-04-21,-0.025520,0.014462,-0.010847,-0.015320,-0.003090,0.006544,-0.015612,-0.012667
2026-04-22,0.025959,0.020442,0.013023,0.020936,0.008753,0.021573,0.002817,0.000064
2026-04-23,0.000951,-0.040469,-0.014224,-0.001268,-0.023347,-0.001097,-0.036235,-0.004258
2026-04-24,-0.008705,0.021111,0.042320,0.016128,0.023806,0.034334,0.006880,-0.011001